var annotated_dup =
[
    [ "Li2", "namespaceLi2.html", [
      [ "GroundTest", "classLi2_1_1GroundTest.html", "classLi2_1_1GroundTest" ]
    ] ],
    [ "Config", "structConfig.html", "structConfig" ],
    [ "Li2_AX25_Header", "structLi2__AX25__Header.html", "structLi2__AX25__Header" ],
    [ "Li2_Beacon_Config", "structLi2__Beacon__Config.html", "structLi2__Beacon__Config" ],
    [ "Li2_Radio", "structLi2__Radio.html", "structLi2__Radio" ],
    [ "Li2_RF_Config", "structLi2__RF__Config.html", "structLi2__RF__Config" ],
    [ "Li2_RTC_Packet", "structLi2__RTC__Packet.html", "structLi2__RTC__Packet" ],
    [ "LI2_SETUP", "structLI2__SETUP.html", "structLI2__SETUP" ],
    [ "Li2_Telemetry_Packet", "structLi2__Telemetry__Packet.html", "structLi2__Telemetry__Packet" ],
    [ "Li2_TXRX_Config", "structLi2__TXRX__Config.html", "structLi2__TXRX__Config" ],
    [ "Li2_UART_Status_Bits", "structLi2__UART__Status__Bits.html", "structLi2__UART__Status__Bits" ],
    [ "Primary", "structPrimary.html", null ],
    [ "Raw", "structRaw.html", null ],
    [ "Scheduler_Task", "structScheduler__Task.html", "structScheduler__Task" ],
    [ "Secondary", "structSecondary.html", null ],
    [ "Transfer_Buff", "structTransfer__Buff.html", "structTransfer__Buff" ],
    [ "TWSG_APID", "structTWSG__APID.html", "structTWSG__APID" ],
    [ "TWSG_Comms_System", "structTWSG__Comms__System.html", "structTWSG__Comms__System" ],
    [ "TWSG_OBC_Abort_Tsk_Payload", "structTWSG__OBC__Abort__Tsk__Payload.html", "structTWSG__OBC__Abort__Tsk__Payload" ],
    [ "TWSG_OBC_Beacon", "structTWSG__OBC__Beacon.html", "structTWSG__OBC__Beacon" ],
    [ "TWSG_OBC_Buff_Cpy_Payload", "structTWSG__OBC__Buff__Cpy__Payload.html", "structTWSG__OBC__Buff__Cpy__Payload" ],
    [ "TWSG_OBC_Buff_Down_Payload", "unionTWSG__OBC__Buff__Down__Payload.html", "unionTWSG__OBC__Buff__Down__Payload" ],
    [ "TWSG_OBC_Buff_Up_Payload", "unionTWSG__OBC__Buff__Up__Payload.html", "unionTWSG__OBC__Buff__Up__Payload" ],
    [ "TWSG_OBC_Handshake", "structTWSG__OBC__Handshake.html", "structTWSG__OBC__Handshake" ],
    [ "TWSG_OBC_Housekeep_Payload", "structTWSG__OBC__Housekeep__Payload.html", "structTWSG__OBC__Housekeep__Payload" ],
    [ "TWSG_OBC_Restart_Payload", "structTWSG__OBC__Restart__Payload.html", "structTWSG__OBC__Restart__Payload" ],
    [ "TWSG_OBC_Schedule_Tsk_Payload", "structTWSG__OBC__Schedule__Tsk__Payload.html", "structTWSG__OBC__Schedule__Tsk__Payload" ],
    [ "TWSG_Pri_Header", "structTWSG__Pri__Header.html", "structTWSG__Pri__Header" ],
    [ "TWSG_Raw_Packet", "structTWSG__Raw__Packet.html", "structTWSG__Raw__Packet" ],
    [ "TWSG_Sec_Header", "structTWSG__Sec__Header.html", "structTWSG__Sec__Header" ]
];