var annotated_dup =
[
    [ "Li2", "namespace_li2.html", [
      [ "GroundTest", "class_li2_1_1_ground_test.html", null ]
    ] ],
    [ "std", null, [
      [ "tr1", null, [
        [ "gtest_internal", null, [
          [ "AddRef", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref.html", null ],
          [ "AddRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4.html", null ],
          [ "ByRef", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html", null ],
          [ "ByRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html", null ],
          [ "Get", "classstd_1_1tr1_1_1gtest__internal_1_1_get.html", null ],
          [ "Get< 0 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html", null ],
          [ "Get< 1 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html", null ],
          [ "Get< 2 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html", null ],
          [ "Get< 3 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html", null ],
          [ "Get< 4 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html", null ],
          [ "Get< 5 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html", null ],
          [ "Get< 6 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html", null ],
          [ "Get< 7 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html", null ],
          [ "Get< 8 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html", null ],
          [ "Get< 9 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html", null ],
          [ "SameSizeTuplePrefixComparator< 0, 0 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator< k, k >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html", null ],
          [ "TupleElement", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element.html", null ],
          [ "TupleElement< true, 0, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 1, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 2, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 3, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 4, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 5, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 6, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 7, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 8, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
          [ "TupleElement< true, 9, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ]
        ] ],
        [ "tuple", "classstd_1_1tr1_1_1tuple.html", null ],
        [ "tuple<>", "classstd_1_1tr1_1_1tuple_3_4.html", null ],
        [ "tuple_element", "structstd_1_1tr1_1_1tuple__element.html", null ],
        [ "tuple_size", "structstd_1_1tr1_1_1tuple__size.html", null ],
        [ "tuple_size< GTEST_0_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__0___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_1_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__1___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_2_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__2___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_3_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__3___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_4_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__4___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_5_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__5___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_6_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__6___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_7_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__7___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_8_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__8___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_9_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__9___t_u_p_l_e___07_t_08_01_4.html", null ]
      ] ]
    ] ],
    [ "testing", null, [
      [ "internal", null, [
        [ "AddReference", "structtesting_1_1internal_1_1_add_reference.html", null ],
        [ "AddReference< T & >", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4.html", null ],
        [ "AssertHelper", "classtesting_1_1internal_1_1_assert_helper.html", null ],
        [ "bool_constant", "structtesting_1_1internal_1_1bool__constant.html", null ],
        [ "CodeLocation", "structtesting_1_1internal_1_1_code_location.html", null ],
        [ "CompileAssert", "structtesting_1_1internal_1_1_compile_assert.html", null ],
        [ "CompileAssertTypesEqual", "structtesting_1_1internal_1_1_compile_assert_types_equal.html", null ],
        [ "CompileAssertTypesEqual< T, T >", "structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html", null ],
        [ "ConstCharPtr", "structtesting_1_1internal_1_1_const_char_ptr.html", null ],
        [ "ConstRef", "structtesting_1_1internal_1_1_const_ref.html", null ],
        [ "ConstRef< T & >", "structtesting_1_1internal_1_1_const_ref_3_01_t_01_6_01_4.html", null ],
        [ "EnableIf", "structtesting_1_1internal_1_1_enable_if.html", null ],
        [ "EnableIf< true >", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html", null ],
        [ "EqHelper", "classtesting_1_1internal_1_1_eq_helper.html", null ],
        [ "EqHelper< true >", "classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html", null ],
        [ "FloatingPoint", "classtesting_1_1internal_1_1_floating_point.html", null ],
        [ "FormatForComparison", "classtesting_1_1internal_1_1_format_for_comparison.html", null ],
        [ "FormatForComparison< ToPrint[N], OtherOperand >", "classtesting_1_1internal_1_1_format_for_comparison_3_01_to_print_0f_n_0e_00_01_other_operand_01_4.html", null ],
        [ "GTestLog", "classtesting_1_1internal_1_1_g_test_log.html", null ],
        [ "GTestMutexLock", "classtesting_1_1internal_1_1_g_test_mutex_lock.html", null ],
        [ "HasValueType", "structtesting_1_1internal_1_1_has_value_type.html", null ],
        [ "HasValueType< T, VoidT< typename T::value_type > >", "structtesting_1_1internal_1_1_has_value_type_3_01_t_00_01_void_t_3_01typename_01_t_1_1value__type_01_4_01_4.html", null ],
        [ "ImplicitlyConvertible", "classtesting_1_1internal_1_1_implicitly_convertible.html", null ],
        [ "is_pointer", "structtesting_1_1internal_1_1is__pointer.html", null ],
        [ "is_pointer< T * >", "structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
        [ "is_same", "structtesting_1_1internal_1_1is__same.html", null ],
        [ "is_same< T, T >", "structtesting_1_1internal_1_1is__same_3_01_t_00_01_t_01_4.html", null ],
        [ "IsAProtocolMessage", "structtesting_1_1internal_1_1_is_a_protocol_message.html", null ],
        [ "IsHashTable", "structtesting_1_1internal_1_1_is_hash_table.html", null ],
        [ "IsRecursiveContainer", "structtesting_1_1internal_1_1_is_recursive_container.html", null ],
        [ "IsRecursiveContainerImpl", "structtesting_1_1internal_1_1_is_recursive_container_impl.html", null ],
        [ "IsRecursiveContainerImpl< C, false, HV >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01false_00_01_h_v_01_4.html", null ],
        [ "IsRecursiveContainerImpl< C, true, false >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01true_00_01false_01_4.html", null ],
        [ "IsRecursiveContainerImpl< C, true, true >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01true_00_01true_01_4.html", null ],
        [ "IsSame", "structtesting_1_1internal_1_1_is_same.html", null ],
        [ "IsSame< T, T >", "structtesting_1_1internal_1_1_is_same_3_01_t_00_01_t_01_4.html", null ],
        [ "IteratorTraits", "structtesting_1_1internal_1_1_iterator_traits.html", null ],
        [ "IteratorTraits< const T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", null ],
        [ "IteratorTraits< T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html", null ],
        [ "linked_ptr", "classtesting_1_1internal_1_1linked__ptr.html", null ],
        [ "linked_ptr_internal", "classtesting_1_1internal_1_1linked__ptr__internal.html", null ],
        [ "Mutex", "classtesting_1_1internal_1_1_mutex.html", null ],
        [ "NativeArray", "classtesting_1_1internal_1_1_native_array.html", null ],
        [ "ParameterizedTestCaseInfo", "classtesting_1_1internal_1_1_parameterized_test_case_info.html", null ],
        [ "ParameterizedTestCaseInfoBase", "classtesting_1_1internal_1_1_parameterized_test_case_info_base.html", null ],
        [ "ParameterizedTestCaseRegistry", "classtesting_1_1internal_1_1_parameterized_test_case_registry.html", null ],
        [ "ParameterizedTestFactory", "classtesting_1_1internal_1_1_parameterized_test_factory.html", null ],
        [ "ParamGenerator", "classtesting_1_1internal_1_1_param_generator.html", null ],
        [ "ParamGeneratorInterface", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
        [ "ParamIterator", "classtesting_1_1internal_1_1_param_iterator.html", null ],
        [ "ParamIteratorInterface", "classtesting_1_1internal_1_1_param_iterator_interface.html", null ],
        [ "ParamNameGenFunc", "structtesting_1_1internal_1_1_param_name_gen_func.html", null ],
        [ "Random", "classtesting_1_1internal_1_1_random.html", null ],
        [ "RangeGenerator", "classtesting_1_1internal_1_1_range_generator.html", null ],
        [ "RE", "classtesting_1_1internal_1_1_r_e.html", null ],
        [ "RelationToSourceCopy", "structtesting_1_1internal_1_1_relation_to_source_copy.html", null ],
        [ "RelationToSourceReference", "structtesting_1_1internal_1_1_relation_to_source_reference.html", null ],
        [ "RemoveConst", "structtesting_1_1internal_1_1_remove_const.html", null ],
        [ "RemoveConst< const T >", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html", null ],
        [ "RemoveConst< const T[N]>", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4.html", null ],
        [ "RemoveReference", "structtesting_1_1internal_1_1_remove_reference.html", null ],
        [ "RemoveReference< T & >", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html", null ],
        [ "RvalueRef", "structtesting_1_1internal_1_1_rvalue_ref.html", null ],
        [ "scoped_ptr", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
        [ "StaticAssertTypeEqHelper", "structtesting_1_1internal_1_1_static_assert_type_eq_helper.html", null ],
        [ "StaticAssertTypeEqHelper< T, T >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html", null ],
        [ "String", "classtesting_1_1internal_1_1_string.html", null ],
        [ "TestFactoryBase", "classtesting_1_1internal_1_1_test_factory_base.html", null ],
        [ "TestFactoryImpl", "classtesting_1_1internal_1_1_test_factory_impl.html", null ],
        [ "TestMetaFactory", "classtesting_1_1internal_1_1_test_meta_factory.html", null ],
        [ "TestMetaFactoryBase", "classtesting_1_1internal_1_1_test_meta_factory_base.html", null ],
        [ "ThreadLocal", "classtesting_1_1internal_1_1_thread_local.html", null ],
        [ "TuplePolicy", "structtesting_1_1internal_1_1_tuple_policy.html", null ],
        [ "TypeIdHelper", "classtesting_1_1internal_1_1_type_id_helper.html", null ],
        [ "TypeWithSize", "classtesting_1_1internal_1_1_type_with_size.html", null ],
        [ "TypeWithSize< 4 >", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4.html", null ],
        [ "TypeWithSize< 8 >", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4.html", null ],
        [ "UniversalPrinter", "classtesting_1_1internal_1_1_universal_printer.html", null ],
        [ "UniversalPrinter< T & >", "classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalPrinter< T[N]>", "classtesting_1_1internal_1_1_universal_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalTersePrinter", "classtesting_1_1internal_1_1_universal_terse_printer.html", null ],
        [ "UniversalTersePrinter< char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< const char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< T & >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalTersePrinter< T[N]>", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalTersePrinter< wchar_t * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html", null ],
        [ "ValueArray1", "classtesting_1_1internal_1_1_value_array1.html", null ],
        [ "ValueArray10", "classtesting_1_1internal_1_1_value_array10.html", null ],
        [ "ValueArray11", "classtesting_1_1internal_1_1_value_array11.html", null ],
        [ "ValueArray12", "classtesting_1_1internal_1_1_value_array12.html", null ],
        [ "ValueArray13", "classtesting_1_1internal_1_1_value_array13.html", null ],
        [ "ValueArray14", "classtesting_1_1internal_1_1_value_array14.html", null ],
        [ "ValueArray15", "classtesting_1_1internal_1_1_value_array15.html", null ],
        [ "ValueArray16", "classtesting_1_1internal_1_1_value_array16.html", null ],
        [ "ValueArray17", "classtesting_1_1internal_1_1_value_array17.html", null ],
        [ "ValueArray18", "classtesting_1_1internal_1_1_value_array18.html", null ],
        [ "ValueArray19", "classtesting_1_1internal_1_1_value_array19.html", null ],
        [ "ValueArray2", "classtesting_1_1internal_1_1_value_array2.html", null ],
        [ "ValueArray20", "classtesting_1_1internal_1_1_value_array20.html", null ],
        [ "ValueArray21", "classtesting_1_1internal_1_1_value_array21.html", null ],
        [ "ValueArray22", "classtesting_1_1internal_1_1_value_array22.html", null ],
        [ "ValueArray23", "classtesting_1_1internal_1_1_value_array23.html", null ],
        [ "ValueArray24", "classtesting_1_1internal_1_1_value_array24.html", null ],
        [ "ValueArray25", "classtesting_1_1internal_1_1_value_array25.html", null ],
        [ "ValueArray26", "classtesting_1_1internal_1_1_value_array26.html", null ],
        [ "ValueArray27", "classtesting_1_1internal_1_1_value_array27.html", null ],
        [ "ValueArray28", "classtesting_1_1internal_1_1_value_array28.html", null ],
        [ "ValueArray29", "classtesting_1_1internal_1_1_value_array29.html", null ],
        [ "ValueArray3", "classtesting_1_1internal_1_1_value_array3.html", null ],
        [ "ValueArray30", "classtesting_1_1internal_1_1_value_array30.html", null ],
        [ "ValueArray31", "classtesting_1_1internal_1_1_value_array31.html", null ],
        [ "ValueArray32", "classtesting_1_1internal_1_1_value_array32.html", null ],
        [ "ValueArray33", "classtesting_1_1internal_1_1_value_array33.html", null ],
        [ "ValueArray34", "classtesting_1_1internal_1_1_value_array34.html", null ],
        [ "ValueArray35", "classtesting_1_1internal_1_1_value_array35.html", null ],
        [ "ValueArray36", "classtesting_1_1internal_1_1_value_array36.html", null ],
        [ "ValueArray37", "classtesting_1_1internal_1_1_value_array37.html", null ],
        [ "ValueArray38", "classtesting_1_1internal_1_1_value_array38.html", null ],
        [ "ValueArray39", "classtesting_1_1internal_1_1_value_array39.html", null ],
        [ "ValueArray4", "classtesting_1_1internal_1_1_value_array4.html", null ],
        [ "ValueArray40", "classtesting_1_1internal_1_1_value_array40.html", null ],
        [ "ValueArray41", "classtesting_1_1internal_1_1_value_array41.html", null ],
        [ "ValueArray42", "classtesting_1_1internal_1_1_value_array42.html", null ],
        [ "ValueArray43", "classtesting_1_1internal_1_1_value_array43.html", null ],
        [ "ValueArray44", "classtesting_1_1internal_1_1_value_array44.html", null ],
        [ "ValueArray45", "classtesting_1_1internal_1_1_value_array45.html", null ],
        [ "ValueArray46", "classtesting_1_1internal_1_1_value_array46.html", null ],
        [ "ValueArray47", "classtesting_1_1internal_1_1_value_array47.html", null ],
        [ "ValueArray48", "classtesting_1_1internal_1_1_value_array48.html", null ],
        [ "ValueArray49", "classtesting_1_1internal_1_1_value_array49.html", null ],
        [ "ValueArray5", "classtesting_1_1internal_1_1_value_array5.html", null ],
        [ "ValueArray50", "classtesting_1_1internal_1_1_value_array50.html", null ],
        [ "ValueArray6", "classtesting_1_1internal_1_1_value_array6.html", null ],
        [ "ValueArray7", "classtesting_1_1internal_1_1_value_array7.html", null ],
        [ "ValueArray8", "classtesting_1_1internal_1_1_value_array8.html", null ],
        [ "ValueArray9", "classtesting_1_1internal_1_1_value_array9.html", null ],
        [ "ValuesInIteratorRangeGenerator", "classtesting_1_1internal_1_1_values_in_iterator_range_generator.html", null ],
        [ "VoidT", "structtesting_1_1internal_1_1_void_t.html", null ],
        [ "WrapPrinterType", "structtesting_1_1internal_1_1_wrap_printer_type.html", null ]
      ] ],
      [ "internal2", null, [
        [ "TypeWithoutFormatter", "classtesting_1_1internal2_1_1_type_without_formatter.html", null ],
        [ "TypeWithoutFormatter< T, kConvertibleToInteger >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_convertible_to_integer_01_4.html", null ],
        [ "TypeWithoutFormatter< T, kProtobuf >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_protobuf_01_4.html", null ]
      ] ],
      [ "EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", null ],
      [ "Environment", "classtesting_1_1_environment.html", null ],
      [ "Message", "classtesting_1_1_message.html", null ],
      [ "PrintToStringParamName", "structtesting_1_1_print_to_string_param_name.html", null ],
      [ "ScopedTrace", "classtesting_1_1_scoped_trace.html", null ],
      [ "Test", "classtesting_1_1_test.html", null ],
      [ "TestCase", "classtesting_1_1_test_case.html", null ],
      [ "TestEventListener", "classtesting_1_1_test_event_listener.html", null ],
      [ "TestEventListeners", "classtesting_1_1_test_event_listeners.html", null ],
      [ "TestInfo", "classtesting_1_1_test_info.html", null ],
      [ "TestParamInfo", "structtesting_1_1_test_param_info.html", null ],
      [ "TestProperty", "classtesting_1_1_test_property.html", null ],
      [ "TestResult", "classtesting_1_1_test_result.html", null ],
      [ "TestWithParam", "classtesting_1_1_test_with_param.html", null ],
      [ "UnitTest", "classtesting_1_1_unit_test.html", null ],
      [ "WithParamInterface", "classtesting_1_1_with_param_interface.html", null ]
    ] ],
    [ "Abacus_imuStatus", "struct_abacus__imu_status.html", null ],
    [ "config", "structconfig.html", null ],
    [ "Config", "struct_config.html", null ],
    [ "configuration", "structconfiguration.html", null ],
    [ "FlashMemory", "struct_flash_memory.html", null ],
    [ "GPIOdigital", "struct_g_p_i_odigital.html", null ],
    [ "GPIOExpander", "struct_g_p_i_o_expander.html", null ],
    [ "I2cPort", "struct_i2c_port.html", null ],
    [ "ini_parse_string_ctx", "structini__parse__string__ctx.html", null ],
    [ "INIReader", "class_i_n_i_reader.html", null ],
    [ "Li2_AX25_Header", "struct_li2___a_x25___header.html", null ],
    [ "Li2_Beacon_Config", "struct_li2___beacon___config.html", "struct_li2___beacon___config" ],
    [ "Li2_Radio", "struct_li2___radio.html", "struct_li2___radio" ],
    [ "Li2_RF_Config", "struct_li2___r_f___config.html", "struct_li2___r_f___config" ],
    [ "Li2_RTC_Packet", "struct_li2___r_t_c___packet.html", "struct_li2___r_t_c___packet" ],
    [ "LI2_SETUP", "struct_l_i2___s_e_t_u_p.html", null ],
    [ "Li2_Telemetry_Packet", "struct_li2___telemetry___packet.html", null ],
    [ "Li2_TXRX_Config", "struct_li2___t_x_r_x___config.html", "struct_li2___t_x_r_x___config" ],
    [ "Li2_UART_Status_Bits", "struct_li2___u_a_r_t___status___bits.html", null ],
    [ "Port", "struct_port.html", null ],
    [ "port_data", "structport__data.html", null ],
    [ "Primary", "struct_primary.html", null ],
    [ "Raw", "struct_raw.html", null ],
    [ "Scheduler_Task", "struct_scheduler___task.html", null ],
    [ "Secondary", "struct_secondary.html", null ],
    [ "SleepTimer", "struct_sleep_timer.html", null ],
    [ "sp_event_set", "structsp__event__set.html", "structsp__event__set" ],
    [ "sp_port", "structsp__port.html", null ],
    [ "sp_port_config", "structsp__port__config.html", null ],
    [ "SPIPort", "struct_s_p_i_port.html", null ],
    [ "std_baudrate", "structstd__baudrate.html", null ],
    [ "time", "structtime.html", null ],
    [ "timeout", "structtimeout.html", null ],
    [ "Transfer_Buff", "struct_transfer___buff.html", null ],
    [ "TWSG_APID", "struct_t_w_s_g___a_p_i_d.html", null ],
    [ "TWSG_Comms_System", "struct_t_w_s_g___comms___system.html", null ],
    [ "TWSG_OBC_Abort_Tsk_Payload", "struct_t_w_s_g___o_b_c___abort___tsk___payload.html", null ],
    [ "TWSG_OBC_Beacon", "struct_t_w_s_g___o_b_c___beacon.html", null ],
    [ "TWSG_OBC_Buff_Cpy_Payload", "struct_t_w_s_g___o_b_c___buff___cpy___payload.html", null ],
    [ "TWSG_OBC_Buff_Down_Payload", "union_t_w_s_g___o_b_c___buff___down___payload.html", null ],
    [ "TWSG_OBC_Buff_Up_Payload", "union_t_w_s_g___o_b_c___buff___up___payload.html", null ],
    [ "TWSG_OBC_Handshake", "struct_t_w_s_g___o_b_c___handshake.html", null ],
    [ "TWSG_OBC_Housekeep_Payload", "struct_t_w_s_g___o_b_c___housekeep___payload.html", null ],
    [ "TWSG_OBC_Restart_Payload", "struct_t_w_s_g___o_b_c___restart___payload.html", null ],
    [ "TWSG_OBC_Schedule_Tsk_Payload", "struct_t_w_s_g___o_b_c___schedule___tsk___payload.html", null ],
    [ "TWSG_Pri_Header", "struct_t_w_s_g___pri___header.html", null ],
    [ "TWSG_Raw_Packet", "struct_t_w_s_g___raw___packet.html", null ],
    [ "TWSG_Sec_Header", "struct_t_w_s_g___sec___header.html", null ]
];