name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
          
      - name: My first step
      - uses: ./.github/workflow/deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: docs/html/Doxyfile
