name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/action.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: docs/html/Doxyfile
